### ISSUE TITLE
Get ModuleNotFoundError when pre-training the model

### ISSUE THREAD

**Issue by Vladimir-Chan** [DeepLearnXMU/CG-RL#2]
Hi,
when I ran the command `sh scripts/django/train-pre.sh`, I got the ModuleNotFoundError as following:

> Traceback (most recent call last):
  File "exp.py", line 35, in <module>
    from model.parser_branch import ParserBranch
ModuleNotFoundError: No module named 'model.parser_branch'

Could you please check the integrity of the project and upload the missing files?
By the way, I got the exception that the package `xgboost` not found before this error. I installed the package and solved it.
Could you please release the conda environment config file?
Thank you.

**Comment by Vladimir-Chan** [comment]
Ok I found that the import statement is not used. I removed it and solved the first problem.

**Comment by lighter47** [comment]
Thanks for your notice bro, I have fixed this bug in new version.
