### ISSUE TITLE
Get RuntimeError when pre-training model

### ISSUE THREAD

**Issue by Vladimir-Chan** [DeepLearnXMU/CG-RL#3]
Hi,
when pre-training the model use the command `bash script/conala/train-pre.sh`, I got the RuntimeError as the following:

> Traceback (most recent call last):                                                            
  File "exp.py", line 615, in <module>                                                        
    pretrain(args)
  File "exp.py", line 500, in pretrain                                                        
    ret_val = model.score(batch_examples, epsilon=1.0)
  File "/home/vladimir/cg-rl/CG-RL-main/model/parser_pre.py", line 313, in score
    query_vectors, new_batch = self.decode_reinforce(batch, src_encodings, dec_init_vec, epsilon=epsilon)
  File "/home/vladimir/cg-rl/CG-RL-main/model/parser_pre.py", line 369, in decode_reinforce
    batch = copy.deepcopy(batch)
  File "/home/vladimir/.conda/envs/cg-rl/lib/python3.6/copy.py", line 180, in deepcopy    
    y = _reconstruct(x, memo, *rv)                                                            
  File "/home/vladimir/.conda/envs/cg-rl/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)                                                             
  File "/home/vladimir/.conda/envs/cg-rl/lib/python3.6/copy.py", line 150, in deepcopy    
    y = copier(x, memo)
  File "/home/vladimir/.conda/envs/cg-rl/lib/python3.6/copy.py", line 240, in _deepcopy_dict   
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/vladimir/.conda/envs/cg-rl/lib/python3.6/copy.py", line 161, in deepcopy    
    y = copier(memo)
  File "/home/vladimir/.conda/envs/cg-rl/lib/python3.6/site-packages/torch/autograd/variable.py", line 91, in __deepcopy__
    raise RuntimeError("Only Variables created explicitly by the user "                       
RuntimeError: Only Variables created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

I think the code `batch = copy.deepcopy(batch)` should be modified to `batch = batch.clone()`, but I' m not sure whether gradient flow should be allowed.
Could you please fix this issue? @lighter47 
Thank you.

**Comment by lighter47** [comment]
I don't have this problem in pytorch 1.3.1, or you can try to use clone() instead of deepcopy(), there is no need for gradient flow.

**Comment by lighter47** [comment]
I don't have this problem in pytorch 1.3.1. You can try to use clone() because there is no need for gradient flow. Thank you for your notification, I will check the version compatibility in the future.

**Comment by Vladimir-Chan** [comment]
> I don't have this problem in pytorch 1.3.1. You can try to use clone() because there is no need for gradient flow. Thank you for your notification, I will check the version compatibility in the future.

Thank you for your response. My pytorch version is 0.3.1, which is same as the [tranx](https://github.com/pcyin/tranX). Could you please release your conda environment config file? 
There are tow copy function, `clone` and `detach`, in pytorch. The gradient should be propagated to the original tensor and I should use `clone` instead of `detach`. Is it right?

**Comment by Vladimir-Chan** [comment]
> I don't have this problem in pytorch 1.3.1. You can try to use clone() because there is no need for gradient flow. Thank you for your notification, I will check the version compatibility in the future.

I found it didn't work because the `batch` is a `Batch` object instead of `Tensor` object. I think the only solution is using the same environment. Could you please release your conda environment config file? The configuration file [config/env/tranx.yml](https://github.com/pcyin/tranX/blob/master/config/env/tranx.yml) mentioned in README file contains only the package name but not the version. Could you please release your configuration file with version? Thank you. @lighter47

**Comment by lighter47** [comment]
I have released two configuration files with python2 and python3 version.

**Comment by Vladimir-Chan** [comment]
Thank you for your response!

**Comment by Vladimir-Chan** [comment]
And it should be removed to make the code more&nbsp;elegant




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DeepLearnXMU/CG-RL] Get RuntimeError when pre-training model (Issue #3)





 
I have released two configuration files with python2 and python3 version.
