### ISSUE TITLE
Got TypeError when pre-trainning model

### ISSUE THREAD

**Issue by Vladimir-Chan** [DeepLearnXMU/CG-RL#4]
Hi,
when pre-trainning model, I got TypeError as the following:

> Traceback (most recent call last):
  File "exp.py", line 615, in <module>
    pretrain(args)
  File "exp.py", line 530, in pretrain
    verbose=True, eval_top_pred_only=args.eval_top_pred_only)
  File "/home/vladimir/cg-rl/CG-RL-main/evaluation.py", line 65, in evaluate
    decode_results = decode(examples, parser, args, verbose=False)
  File "/home/vladimir/cg-rl/CG-RL-main/evaluation.py", line 26, in decode
    hyps = model.parse(example.src_sent, context=None, beam_size=args.beam_size)
  File "/home/vladimir/cg-rl/CG-RL-main/model/parser_pre.py", line 777, in parse
    token = primitive_vocab.id2word[token_id.item()]
TypeError: 'method' object is not subscriptable

After checking the class `VocabEntry` I found the member variable `id2word` defined in line 18 has the same name with the member method defined in line 35. I think the member method is redundant and should be removed. Is it right? @lighter47

**Comment by lighter47** [comment]
No, this class is from Tranx and no problem. I can't tell the reason, maybe you can send me more information via email.

**Comment by Vladimir-Chan** [comment]
Uhh, I don't know the reason, too. I met this problem when using the dataset built by myself. The environment is the same as your Python3 environment. However, I think the member method `id2word` in line 35 of the file `components/vocab.py` is&nbsp;redundant, and removing it could solve this problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月12日(星期二) 晚上7:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DeepLearnXMU/CG-RL] Got TypeError when pre-trainning model (Issue #4)





 
No, this class is from Tranx and no problem. I can't tell the reason, maybe you can send me more information via email.

**Comment by Vladimir-Chan** [comment]
Ok I found the reason. I process my dataset using the latest  version of [tranx](https://github.com/pcyin/tranX/tree/master), but the file `components/vocab.py` in your code is the previous version of [tranx](https://github.com/pcyin/tranX/tree/acl2019_rerank). There are some differences between the two versions in the class `VocabEntry`.

**Comment by Vladimir-Chan** [comment]
And I found the package `dataset` should be in your code. Could you please add the package to your code? @lighter47

**Comment by XiaoXiaoYi123** [comment]
have you solved this problem? @Vladimir-Chan

**Comment by Vladimir-Chan** [comment]
> have you solved this problem? @Vladimir-Chan

If I remember correctly, using Pytorch 1.3.0 may be helpful.
